"""
switchback.coverage: the living answer to "which parks are in?"

Hand-maintained coverage lists rot (the 2026-07-12 doc audit proved it),
so this generates the list from the repo's actual state. Tiers:

  Tier 0  the availability finder works on EVERY recreation.gov permit
          today with zero setup; nothing needs to be "added" for that
  Tier 1  dataset built (extract + features): camps, coords, lakes,
          elevations; caltopo export and features work
  Tier 2  trips-ready: a route graph exists, so trips, watch, GPX,
          day hikes, and scoring all work on its corridors

python -m switchback coverage [--write] regenerates coverage/COVERAGE.md.
"""
import glob
import json
import os
from datetime import datetime, timezone

COVERAGE_MD = "coverage/COVERAGE.md"
_SKIP = {"manual_coords.json", "ratings.json", "demand.json"}


def survey():
    rows = []
    for p in sorted(glob.glob(os.path.join("parks", "*.json"))):
        if os.path.basename(p) in _SKIP:
            continue
        try:
            d = json.load(open(p))
        except (OSError, ValueError):
            continue
        if d.get("region"):
            from .extract import load_park
            d = load_park(d["slug"])
        c = d.get("counts", {})
        row = {"slug": d.get("slug"), "name": d.get("name"),
               "region": bool(d.get("region")),
               "permit_id": d.get("permit_id"),
               "camps": c.get("camps_included"),
               "coords": sum(1 for x in d.get("camps", [])
                             if x.get("included") and x.get("lat") is not None),
               "graph_camps": None, "edges": None, "sourced": None}
        try:
            from .graph import Graph
            g = Graph(row["slug"])
            row["graph_camps"] = len(g.camps())
            row["edges"] = g.sourced_edges + g.est_edges
            row["sourced"] = g.sourced_edges
        except Exception:
            pass
        rows.append(row)
    try:
        manual = json.load(open(os.path.join("parks", "manual_coords.json")))
        queue = {k: len([x for x in v if not str(x).startswith("_")])
                 for k, v in manual.items() if isinstance(v, dict)}
    except (OSError, ValueError):
        queue = {}
    return rows, queue


def render(rows, queue):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = ["# Switchback coverage",
           "",
           f"Generated by `python -m switchback coverage --write` on {ts}. "
           "Do not edit by hand; rerun the command.",
           "",
           "Tier 0 is universal: the availability finder (GUI and CLI) works "
           "on every recreation.gov permit, park or forest, with zero setup. "
           "The table below tracks the deeper tiers. Tier 1 means the park "
           "dataset exists (extract plus features). Tier 2 means a route "
           "graph exists, so trips, watch, GPX, day hikes, and scoring work "
           "on its transcribed corridors.",
           "",
           "| Park | Permit | Camps (with coords) | Graph camps | Edges (sourced gains) | Tier |",
           "|---|---|---|---|---|---|"]
    for r in rows:
        tier = "2: trips-ready" if r["edges"] else "1: dataset"
        if r.get("region"):
            tier += " (region)"
        edges = (f"{r['edges']} ({r['sourced']})" if r["edges"] else "none")
        gc = r["graph_camps"] if r["graph_camps"] else ""
        out.append(f"| {r['name']} | {r['permit_id']} | "
                   f"{r['camps']} ({r['coords']}) | {gc} | {edges} | {tier} |")
    if queue:
        q = ", ".join(f"{k}: {v}" for k, v in sorted(queue.items()) if v)
        if q:
            out.append("")
            out.append(f"Open coordinate queue (parks/manual_coords.json): {q}.")
    out.append("")
    out.append("Expansion sequencing lives in BACKLOG.md under the park and "
               "forest expansion plan; the cross-boundary region concept "
               "(linking parks and forests that share trails, Lena corridor "
               "pilot) is tracked there too.")
    out.append("")
    text = "\n".join(out)
    return text.replace("\u2013", "-").replace("\u2014", "-")


def write_coverage():
    """One coverage truth file. coverage/COVERAGE.md carries the trip-ready tier
    table plus both state atlases; COLORADO.md, WASHINGTON.md, and
    PARKS.md are retired (v3.3.1 consolidation). Both the atlas and
    coverage CLI commands regenerate the whole file."""
    import json as _json
    rows, queue = survey()
    parts = [render(rows, queue).replace(
        "# Switchback coverage",
        "# COVERAGE.md\n\nThe single coverage truth: trip-ready tiers "
        "first, then the full state atlases. Mapped does not mean "
        "plannable; the tier column is the truth.\n\n## Trip-ready "
        "datasets", 1)]
    data = _json.load(open("parks/atlas.json"))
    total = 0
    for state, title in (("CO", "Colorado"), ("WA", "Washington")):
        srows = [r for r in data["rows"] if r.get("state") == state]
        total += len(srows)
        parts.append(_render_state(srows, title).replace(
            f"# {title} coverage atlas", f"## {title} atlas", 1))
    with open(COVERAGE_MD, "w") as fh:
        fh.write("\n".join(parts))
    return total


def render_atlas():
    return write_coverage()


def _render_state(rows, title):

    import json as _json
    import json as _json
    legend = {"live": "live (bookable itineraries)", "map": "trails on the map",
              "planned": "planned", "not-suitable": "not suitable"}
    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    out = [f"# {title} coverage atlas", "",
           f"Every {title} backpacking landscape Switchback tracks, from rec.gov",
           "quota systems to fully dispersed wilderness. Generated from",
           "parks/atlas.json; edit the JSON, not this file.", "",
           "Status counts: " + ", ".join(f"{counts.get(k,0)} {v}"
                                          for k, v in legend.items()), ""]
    for cat, title in (("NPS", "National parks"),
                       ("USFS wilderness", "Wilderness areas (USFS)"),
                       ("BLM", "BLM lands"), ("other", "Other public lands"),
                       ("long trail", "Long trails")):
        sub = [r for r in rows if r["cat"] == cat]
        if not sub:
            continue
        out += [f"## {title}", "", "| Area | Permit | Status | Notes |",
                "|---|---|---|---|"]
        order = {"live": 0, "map": 1, "planned": 2, "not-suitable": 3}
        for r in sorted(sub, key=lambda x: (order[x["status"]], x["name"])):
            out.append(f"| {r['name']} | {r['permit']} | {legend[r['status']]} "
                       f"| {r.get('notes','')} |")
        out.append("")
    text = "\n".join(out) + "\n"
    return text.replace("\u2013", "-").replace("\u2014", "-")
