"""
switchback.coverage: the living answer to "which parks are in?"

Hand-maintained coverage lists rot (the 2026-07-12 doc audit proved it),
so this generates the list from the repo's actual state. Tiers:

  Tier 0  the availability finder works on EVERY recreation.gov permit
          today with zero setup; nothing needs to be "added" for that
  Tier 1  dataset built (extract + features): camps, coords, lakes,
          elevations; caltopo export and features work
  Tier 2  trips-ready: a route graph exists, so trips, watch, GPX,
          day hikes, and scoring all work on its corridors

python -m switchback coverage [--write] regenerates PARKS.md.
"""
import glob
import json
import os
from datetime import datetime, timezone

PARKS_MD = "PARKS.md"
_SKIP = {"manual_coords.json", "ratings.json", "demand.json"}


def survey():
    rows = []
    for p in sorted(glob.glob(os.path.join("parks", "*.json"))):
        if os.path.basename(p) in _SKIP:
            continue
        try:
            d = json.load(open(p))
        except (OSError, ValueError):
            continue
        if d.get("region"):
            from .extract import load_park
            d = load_park(d["slug"])
        c = d.get("counts", {})
        row = {"slug": d.get("slug"), "name": d.get("name"),
               "region": bool(d.get("region")),
               "permit_id": d.get("permit_id"),
               "camps": c.get("camps_included"),
               "coords": sum(1 for x in d.get("camps", [])
                             if x.get("included") and x.get("lat") is not None),
               "graph_camps": None, "edges": None, "sourced": None}
        try:
            from .graph import Graph
            g = Graph(row["slug"])
            row["graph_camps"] = len(g.camps())
            row["edges"] = g.sourced_edges + g.est_edges
            row["sourced"] = g.sourced_edges
        except Exception:
            pass
        rows.append(row)
    try:
        manual = json.load(open(os.path.join("parks", "manual_coords.json")))
        queue = {k: len([x for x in v if not str(x).startswith("_")])
                 for k, v in manual.items() if isinstance(v, dict)}
    except (OSError, ValueError):
        queue = {}
    return rows, queue


def render(rows, queue):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = ["# Switchback coverage",
           "",
           f"Generated by `python -m switchback coverage --write` on {ts}. "
           "Do not edit by hand; rerun the command.",
           "",
           "Tier 0 is universal: the availability finder (GUI and CLI) works "
           "on every recreation.gov permit, park or forest, with zero setup. "
           "The table below tracks the deeper tiers. Tier 1 means the park "
           "dataset exists (extract plus features). Tier 2 means a route "
           "graph exists, so trips, watch, GPX, day hikes, and scoring work "
           "on its transcribed corridors.",
           "",
           "| Park | Permit | Camps (with coords) | Graph camps | Edges (sourced gains) | Tier |",
           "|---|---|---|---|---|---|"]
    for r in rows:
        tier = "2: trips-ready" if r["edges"] else "1: dataset"
        if r.get("region"):
            tier += " (region)"
        edges = (f"{r['edges']} ({r['sourced']})" if r["edges"] else "none")
        gc = r["graph_camps"] if r["graph_camps"] else ""
        out.append(f"| {r['name']} | {r['permit_id']} | "
                   f"{r['camps']} ({r['coords']}) | {gc} | {edges} | {tier} |")
    if queue:
        q = ", ".join(f"{k}: {v}" for k, v in sorted(queue.items()) if v)
        if q:
            out.append("")
            out.append(f"Open coordinate queue (parks/manual_coords.json): {q}.")
    out.append("")
    out.append("Expansion sequencing lives in BACKLOG.md under the park and "
               "forest expansion plan; the cross-boundary region concept "
               "(linking parks and forests that share trails, Lena corridor "
               "pilot) is tracked there too.")
    out.append("")
    return "\n".join(out)
